src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_added = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $destocking_date = null;

    #[ORM\Column(length: 255)]
    private ?string $serial_number = null;

    #[ORM\Column]
    private ?bool $state = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Invoice $invoice = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateAdded(): ?\DateTimeInterface
    {
        return $this->date_added;
    }

    public function setDateAdded(\DateTimeInterface $date_added): self
    {
        $this->date_added = $date_added;

        return $this;
    }

    public function getDestockingDate(): ?\DateTimeInterface
    {
        return $this->destocking_date;
    }

    public function setDestockingDate(?\DateTimeInterface $destocking_date): self
    {
        $this->destocking_date = $destocking_date;

        return $this;
    }

    public function getSerialNumber(): ?string
    {
        return $this->serial_number;
    }

    public function setSerialNumber(string $serial_number): self
    {
        $this->serial_number = $serial_number;

        return $this;
    }

    public function isState(): ?bool
    {
        return $this->state;
    }

    public function setState(bool $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getInvoice(): ?Invoice
    {
        return $this->invoice;
    }

    public function setInvoice(?Invoice $invoice): self
    {
        $this->invoice = $invoice;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextareaType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('date_added', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'attr' => ['class' => 'form-control'],
            ])
            ->add('serial_number', TextareaType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            //->add('destocking_date')
            //->add('state')
            //->add('invoice')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use App\Repository\CategoryRepository;
use DateTime;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Date;

#[Route('/article')]
class ArticleController extends AbstractController
{
    #[Route('/', name: 'app_article_index', methods: ['GET'])]
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_article_new', methods: ['GET', 'POST'])]
    public function new(Request $request,ManagerRegistry $doctrine, ArticleRepository $articleRepository, CategoryRepository $categoryRepository): Response
    {   
        $entityManager = $doctrine->getManager();
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);
        $requestAll = $request->request->all();



        if ($form->isSubmitted() && $form->isValid()) {
            //dd($request);
            $articleToAdd = new Article();
            $name = $requestAll['article']['name'];
            $articleToAdd->setName($name);
            $date = new DateTime($requestAll['article']['date_added']);
            $articleToAdd->setDateAdded($date);
            $sn = $requestAll['article']['serial_number'];
            $articleToAdd->setSerialNumber($sn);
            $category = $categoryRepository->findOneById($requestAll['article']['category']);
            $articleToAdd->setCategory($category);
            $state = 0;
            $articleToAdd->setState($state);

            $entityManager->persist($articleToAdd);
            $entityManager->flush();
            
            //$articleRepository->save($article, true);

            return $this->redirectToRoute('app_article_new', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_show', methods: ['GET'])]
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_article_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Article $article, ArticleRepository $articleRepository): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articleRepository->save($article, true);

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_delete', methods: ['POST'])]
    public function delete(Request $request, Article $article, ArticleRepository $articleRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $articleRepository->remove($article, true);
        }

        return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('app_article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Edit Article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
    <div class="justify-content-center mt-5 pt-5 container-fluid col-6">

        <h1>Article index</h1>

        <table class="table">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Date d'ajout</th>
                    <th>Date de destockage</th>
                    <th>Serial Number</th>
                    <th>Etat</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for article in articles %}
                <tr>
                    <td>{{ article.name }}</td>
                    <td>{{ article.dateAdded ? article.dateAdded|date('Y-m-d') : '' }}</td>
                    <td>{{ article.destockingDate ? article.destockingDate|date('Y-m-d') : '' }}</td>
                    <td>{{ article.serialNumber }}</td>
                    <td>{{ article.state ? 'Epuisé' : 'En stock' }}</td>
                    <td>
                        <a href="{{ path('app_article_edit', {'id': article.id}) }}">Modifier</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="7">Aucun article</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_article_new') }}">Ajouter un article</a>
    </div>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un article{% endblock %}

{% block body %}
    <div class="justify-content-center mt-5 pt-5 container-fluid col-6">
        <h1>Ajouter un nouvel article</h1>
            {{ form_start(form) }}
            <div class='form-group'>
                <label for="name" class='col-5'>Nom de l'article :</label>
                {{ form_widget(form.name)}}
            </div>
            <div class='form-group'>    
                <label for="date_added" class='col-5'>Date d'ajout :</label>
                {{ form_widget(form.date_added)}}
            </div>
            <div class='form-group'>
                <label for="category" class='col-5'>Categorie :</label>
                {{ form_widget(form.category)}}
            </div>
            <div class='form-group'>
                <label for="serial_number" class='col-5'>S/N :</label>
                {{ form_widget(form.serial_number)}}
            </div>
            <div class='form-group'>
                <button type="submit" class="btn btn-primary mt-5">Enregistrer</button>
            </div>
            {{ form_end(form)}}
        </div>
    </div>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h1>Article</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ article.name }}</td>
            </tr>
            <tr>
                <th>Date_added</th>
                <td>{{ article.dateAdded ? article.dateAdded|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Destocking_date</th>
                <td>{{ article.destockingDate ? article.destockingDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Serial_number</th>
                <td>{{ article.serialNumber }}</td>
            </tr>
            <tr>
                <th>State</th>
                <td>{{ article.state ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_article_index') }}">back to list</a>

    <a href="{{ path('app_article_edit', {'id': article.id}) }}">edit</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}